version: '3'

dotenv: [".env"]

tasks:
  run:
    cmds:
      - poetry run start
    dir: ./backend

  worker:
    cmds:
      - LOGLEVEL=DEBUG arq src.intric.worker.arq.WorkerSettings
    dir: ./backend

  frontend:
    cmds:
      - npm run dev
    dir: ./frontend

  migrate:
    cmds:
      - alembic upgrade head
    dir: ./backend
